package trinarybrain.magia.naturalis.coremod;

import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import trinarybrain.magia.naturalis.common.core.Log;

public class ProfileMethod extends MethodVisitor implements Opcodes
{
	private String className;
	private String methodName;

	public ProfileMethod(MethodVisitor mv, int access, String className, String methodName, String desc, String signature)
	{
		super(ASM4, mv);
		this.className = className;
		this.methodName = methodName;
		
		Log.logger.info("Profiling " + methodName + " in class " + className);
		
		if(methodName.equals(Mapping.m_renderModel[Agent.dev]))
		{
			Log.logger.info("==========> DEV: " + Agent.dev);
			Log.logger.info("==========> Profiling " + methodName + " in class " + className);
			Log.logger.info("==========> Current Access: " + access + "Vs. Protected Acces: " + Opcodes.ACC_PROTECTED);
			Log.logger.info("==========> Description: " + desc);
			Log.logger.info("==========> signature: " + signature);
		}
		
		if(methodName.equals("renderModel"))
		{
			Log.logger.info("Profiled class " + className+ ".");
			Log.logger.info("Replacing " + methodName + " Method Body.");
			mv.visitCode();
			Label l0 = new Label();
			mv.visitLabel(l0);
			mv.visitLineNumber(61, l0);
			mv.visitVarInsn(Opcodes.ALOAD, 0);
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, Mapping.r_RendererLivingEntity[Agent.dev], Mapping.m_bindEntityTexture[Agent.dev], "(L" + Mapping.r_Entity[Agent.dev] + ";)V", false);
			Label l1 = new Label();
			mv.visitLabel(l1);
			mv.visitLineNumber(62, l1);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, Mapping.r_Minecraft[Agent.dev], Mapping.m_getMinecraft[Agent.dev], "()L" + Mapping.r_Minecraft[Agent.dev] + ";", false);
			mv.visitFieldInsn(Opcodes.GETFIELD, Mapping.r_Minecraft[Agent.dev], Mapping.f_thePlayer[Agent.dev], "L" + Mapping.r_EntityClientPlayerMP[Agent.dev] +";");
			mv.visitVarInsn(Opcodes.ASTORE, 8);
			Label l2 = new Label();
			mv.visitLabel(l2);
			mv.visitLineNumber(63, l2);
			mv.visitVarInsn(Opcodes.ALOAD, 8);
			mv.visitFieldInsn(Opcodes.GETFIELD, Mapping.r_EntityPlayer[Agent.dev], Mapping.f_inventory[Agent.dev], "L" + Mapping.r_InventoryPlayer + ";");
			mv.visitInsn(Opcodes.ICONST_3);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, Mapping.r_EntityPlayer[Agent.dev], "armorItemInSlot", "(I)Lnet/minecraft/item/ItemStack;", false);
			mv.visitVarInsn(Opcodes.ASTORE, 9);
			Label l3 = new Label();
			mv.visitLabel(l3);
			mv.visitLineNumber(65, l3);
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, Mapping.r_EntityLivingBase[Agent.dev], Mapping.m_isInvisible[Agent.dev], "()Z", false);
			Label l4 = new Label();
			mv.visitJumpInsn(Opcodes.IFNE, l4);
			Label l5 = new Label();
			mv.visitLabel(l5);
			mv.visitLineNumber(67, l5);
			mv.visitVarInsn(Opcodes.ALOAD, 0);
			mv.visitFieldInsn(Opcodes.GETFIELD, Mapping.r_RendererLivingEntity[Agent.dev], Mapping.f_mainModel[Agent.dev], "Lnet/minecraft/client/model/ModelBase;");
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitVarInsn(Opcodes.FLOAD, 2);
			mv.visitVarInsn(Opcodes.FLOAD, 3);
			mv.visitVarInsn(Opcodes.FLOAD, 4);
			mv.visitVarInsn(Opcodes.FLOAD, 5);
			mv.visitVarInsn(Opcodes.FLOAD, 6);
			mv.visitVarInsn(Opcodes.FLOAD, 7);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "net/minecraft/client/model/ModelBase", "render", "(Lnet/minecraft/entity/Entity;FFFFFF)V", false);
			Label l6 = new Label();
			mv.visitLabel(l6);
			mv.visitLineNumber(68, l6);
			Label l7 = new Label();
			mv.visitJumpInsn(Opcodes.GOTO, l7);
			mv.visitLabel(l4);
			mv.visitLineNumber(69, l4);
			mv.visitFrame(Opcodes.F_APPEND,2, new Object[] {"net/minecraft/entity/player/EntityPlayer", "net/minecraft/item/ItemStack"}, 0, null);
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitVarInsn(Opcodes.ALOAD, 8);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, Mapping.r_EntityLivingBase[Agent.dev], "isInvisibleToPlayer", "(L" + Mapping.r_EntityPlayer[Agent.dev] + ";)Z", false);
			Label l8 = new Label();
			mv.visitJumpInsn(Opcodes.IFEQ, l8);
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitVarInsn(Opcodes.ALOAD, 8);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, Mapping.r_EntityLivingBase[Agent.dev], "isInvisibleToPlayer", "(L" + Mapping.r_EntityPlayer[Agent.dev] + ";)Z", false);
			Label l9 = new Label();
			mv.visitJumpInsn(Opcodes.IFEQ, l9);
			mv.visitVarInsn(Opcodes.ALOAD, 9);
			mv.visitJumpInsn(Opcodes.IFNULL, l9);
			mv.visitVarInsn(Opcodes.ALOAD, 9);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "net/minecraft/item/ItemStack", "getItem", "()Lnet/minecraft/item/Item;", false);
			mv.visitTypeInsn(Opcodes.INSTANCEOF, "trinarybrain/magianaturalis/api/IRevealInvisible");
			mv.visitJumpInsn(Opcodes.IFEQ, l9);
			mv.visitVarInsn(Opcodes.ALOAD, 9);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "net/minecraft/item/ItemStack", "getItem", "()Lnet/minecraft/item/Item;", false);
			mv.visitTypeInsn(Opcodes.CHECKCAST, "trinarybrain/magianaturalis/api/IRevealInvisible");
			mv.visitVarInsn(Opcodes.ALOAD, 9);
			mv.visitVarInsn(Opcodes.ALOAD, 8);
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitMethodInsn(Opcodes.INVOKEINTERFACE, "trinarybrain/magianaturalis/api/IRevealInvisible", "showInvisibleEntity", "(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/entity/EntityLivingBase;)Z", true);
			mv.visitJumpInsn(Opcodes.IFEQ, l9);
			mv.visitLabel(l8);
			mv.visitLineNumber(71, l8);
			mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glPushMatrix", "()V", false);
			Label l10 = new Label();
			mv.visitLabel(l10);
			mv.visitLineNumber(72, l10);
			mv.visitInsn(Opcodes.FCONST_1);
			mv.visitInsn(Opcodes.FCONST_1);
			mv.visitInsn(Opcodes.FCONST_1);
			mv.visitLdcInsn(new Float("0.15"));
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glColor4f", "(FFFF)V", false);
			Label l11 = new Label();
			mv.visitLabel(l11);
			mv.visitLineNumber(73, l11);
			mv.visitInsn(Opcodes.ICONST_0);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDepthMask", "(Z)V", false);
			Label l12 = new Label();
			mv.visitLabel(l12);
			mv.visitLineNumber(74, l12);
			mv.visitIntInsn(Opcodes.SIPUSH, 3042);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glEnable", "(I)V", false);
			Label l13 = new Label();
			mv.visitLabel(l13);
			mv.visitLineNumber(75, l13);
			mv.visitIntInsn(Opcodes.SIPUSH, 770);
			mv.visitIntInsn(Opcodes.SIPUSH, 771);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glBlendFunc", "(II)V", false);
			Label l14 = new Label();
			mv.visitLabel(l14);
			mv.visitLineNumber(76, l14);
			mv.visitIntInsn(Opcodes.SIPUSH, 516);
			mv.visitLdcInsn(new Float("0.003921569"));
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glAlphaFunc", "(IF)V", false);
			Label l15 = new Label();
			mv.visitLabel(l15);
			mv.visitLineNumber(77, l15);
			mv.visitVarInsn(Opcodes.ALOAD, 0);
			mv.visitFieldInsn(Opcodes.GETFIELD, "net/minecraft/client/renderer/entity/RendererLivingEntity", "mainModel", "Lnet/minecraft/client/model/ModelBase;");
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitVarInsn(Opcodes.FLOAD, 2);
			mv.visitVarInsn(Opcodes.FLOAD, 3);
			mv.visitVarInsn(Opcodes.FLOAD, 4);
			mv.visitVarInsn(Opcodes.FLOAD, 5);
			mv.visitVarInsn(Opcodes.FLOAD, 6);
			mv.visitVarInsn(Opcodes.FLOAD, 7);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "net/minecraft/client/model/ModelBase", "render", "(Lnet/minecraft/entity/Entity;FFFFFF)V", false);
			Label l16 = new Label();
			mv.visitLabel(l16);
			mv.visitLineNumber(78, l16);
			mv.visitIntInsn(Opcodes.SIPUSH, 3042);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDisable", "(I)V", false);
			Label l17 = new Label();
			mv.visitLabel(l17);
			mv.visitLineNumber(79, l17);
			mv.visitIntInsn(Opcodes.SIPUSH, 516);
			mv.visitLdcInsn(new Float("0.1"));
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glAlphaFunc", "(IF)V", false);
			Label l18 = new Label();
			mv.visitLabel(l18);
			mv.visitLineNumber(80, l18);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glPopMatrix", "()V", false);
			Label l19 = new Label();
			mv.visitLabel(l19);
			mv.visitLineNumber(81, l19);
			mv.visitInsn(Opcodes.ICONST_1);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDepthMask", "(Z)V", false);
			Label l20 = new Label();
			mv.visitLabel(l20);
			mv.visitLineNumber(82, l20);
			mv.visitJumpInsn(Opcodes.GOTO, l7);
			mv.visitLabel(l9);
			mv.visitLineNumber(85, l9);
			mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
			mv.visitVarInsn(Opcodes.ALOAD, 0);
			mv.visitFieldInsn(Opcodes.GETFIELD, "net/minecraft/client/renderer/entity/RendererLivingEntity", "mainModel", "Lnet/minecraft/client/model/ModelBase;");
			mv.visitVarInsn(Opcodes.FLOAD, 2);
			mv.visitVarInsn(Opcodes.FLOAD, 3);
			mv.visitVarInsn(Opcodes.FLOAD, 4);
			mv.visitVarInsn(Opcodes.FLOAD, 5);
			mv.visitVarInsn(Opcodes.FLOAD, 6);
			mv.visitVarInsn(Opcodes.FLOAD, 7);
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, "net/minecraft/client/model/ModelBase", "setRotationAngles", "(FFFFFFLnet/minecraft/entity/Entity;)V", false);
			mv.visitLabel(l7);
			mv.visitLineNumber(87, l7);
			mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
			mv.visitInsn(Opcodes.RETURN);
			Label l21 = new Label();
			mv.visitLabel(l21);
			mv.visitLocalVariable("this", "Lnet/minecraft/client/renderer/entity/RendererLivingEntity;", null, l0, l21, 0);
			mv.visitLocalVariable("p_77036_1_", "Lnet/minecraft/entity/EntityLivingBase;", null, l0, l21, 1);
			mv.visitLocalVariable("p_77036_2_", "F", null, l0, l21, 2);
			mv.visitLocalVariable("p_77036_3_", "F", null, l0, l21, 3);
			mv.visitLocalVariable("p_77036_4_", "F", null, l0, l21, 4);
			mv.visitLocalVariable("p_77036_5_", "F", null, l0, l21, 5);
			mv.visitLocalVariable("p_77036_6_", "F", null, l0, l21, 6);
			mv.visitLocalVariable("p_77036_7_", "F", null, l0, l21, 7);
			mv.visitLocalVariable("player", "L" + Mapping.r_EntityPlayer[Agent.dev] + ";", null, l2, l21, 8);
			mv.visitLocalVariable("stack", "Lnet/minecraft/item/ItemStack;", null, l3, l21, 9);
			mv.visitMaxs(8, 10);
			mv.visitEnd();
		}
	}
}
