package trinarybrain.magia.naturalis.coremod;

import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraftforge.common.util.FakePlayer;

import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import trinarybrain.magia.naturalis.common.core.Log;

public class ProfileMethod extends MethodVisitor implements Opcodes
{
	private String className;
	private String methodName;

	public ProfileMethod(MethodVisitor mv, String className, String methodName, String desc)
	{
		super(ASM4, mv);
		this.className = className;
		this.methodName = methodName;

		// (Lnet/minecraft/entity/EntityLivingBase;FFFFFF)V
		// (Lsv;FFFFFF)V
		if(methodName.equals(ObfMapCollector.getMapping("renderModel")) && desc.equals("(L" + ObfMapCollector.getMapping("net/minecraft/entity/EntityLivingBase") + ";FFFFFF)V"))
		{
			Log.logger.info("Profiling Class: " + className+ ".");
			this.mv = null; //set the current method visitor null in order to removes the old method
			Log.logger.info("Replacing " + methodName + "(" + desc +") Method-Body in class.");

			mv.visitCode();
			Label l0 = new Label();
			mv.visitLabel(l0);
			mv.visitLineNumber(22, l0);
			mv.visitVarInsn(ALOAD, 0);
			mv.visitVarInsn(ALOAD, 1);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/client/renderer/entity/RendererLivingEntity"), ObfMapCollector.getMapping("bindEntityTexture"), "(L" + ObfMapCollector.getMapping("net/minecraft/entity/Entity") + ";)V", false);
			Label l1 = new Label();
			mv.visitLabel(l1);
			mv.visitLineNumber(23, l1);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, ObfMapCollector.getMapping("net/minecraft/client/Minecraft"), ObfMapCollector.getMapping("getMinecraft"), "()L" + ObfMapCollector.getMapping("net/minecraft/client/Minecraft") + ";", false);
			mv.visitFieldInsn(Opcodes.GETFIELD, ObfMapCollector.getMapping("net/minecraft/client/Minecraft"), ObfMapCollector.getMapping("thePlayer"), "L" + ObfMapCollector.getMapping("net/minecraft/client/entity/EntityClientPlayerMP") + ";");
			mv.visitVarInsn(ASTORE, 8);
			Label l2 = new Label();
			mv.visitLabel(l2);
			mv.visitLineNumber(24, l2);
			mv.visitInsn(ACONST_NULL);
			mv.visitVarInsn(ASTORE, 9);
			Label l3 = new Label();
			mv.visitLabel(l3);
			mv.visitLineNumber(25, l3);
			mv.visitVarInsn(ALOAD, 8);
			Label l4 = new Label();
			mv.visitJumpInsn(IFNULL, l4);
			mv.visitVarInsn(ALOAD, 8);
			mv.visitFieldInsn(Opcodes.GETFIELD, ObfMapCollector.getMapping("net/minecraft/entity/player/EntityPlayer"), ObfMapCollector.getMapping("inventory"), "L" + ObfMapCollector.getMapping("net/minecraft/entity/player/InventoryPlayer") + ";");
			mv.visitJumpInsn(IFNULL, l4);
			Label l5 = new Label();
			mv.visitLabel(l5);
			mv.visitLineNumber(27, l5);
			mv.visitVarInsn(ALOAD, 8);
			mv.visitFieldInsn(Opcodes.GETFIELD, ObfMapCollector.getMapping("net/minecraft/entity/player/EntityPlayer"), ObfMapCollector.getMapping("inventory"), "L" + ObfMapCollector.getMapping("net/minecraft/entity/player/InventoryPlayer") + ";");
			mv.visitInsn(ICONST_3);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/entity/player/InventoryPlayer"), ObfMapCollector.getMapping("armorItemInSlot"), "(I)L" + ObfMapCollector.getMapping("net/minecraft/item/ItemStack") + ";", false);
			mv.visitVarInsn(ASTORE, 9);
			mv.visitLabel(l4);
			mv.visitLineNumber(30, l4);
			mv.visitFrame(Opcodes.F_APPEND,2, new Object[] {ObfMapCollector.getMapping("net/minecraft/entity/player/EntityPlayer"), ObfMapCollector.getMapping("net/minecraft/item/ItemStack")}, 0, null);
			mv.visitVarInsn(ALOAD, 1);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/entity/EntityLivingBase"), ObfMapCollector.getMapping("isInvisible"), "()Z", false);
			Label l6 = new Label();
			mv.visitJumpInsn(IFNE, l6);
			Label l7 = new Label();
			mv.visitLabel(l7);
			mv.visitLineNumber(32, l7);
			mv.visitVarInsn(ALOAD, 0);
			mv.visitFieldInsn(Opcodes.GETFIELD, ObfMapCollector.getMapping("net/minecraft/client/renderer/entity/RendererLivingEntity"), ObfMapCollector.getMapping("mainModel"), "L" + ObfMapCollector.getMapping("net/minecraft/client/model/ModelBase") + ";");
			mv.visitVarInsn(ALOAD, 1);
			mv.visitVarInsn(FLOAD, 2);
			mv.visitVarInsn(FLOAD, 3);
			mv.visitVarInsn(FLOAD, 4);
			mv.visitVarInsn(FLOAD, 5);
			mv.visitVarInsn(FLOAD, 6);
			mv.visitVarInsn(FLOAD, 7);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/client/model/ModelBase"), ObfMapCollector.getMapping("render"), "(L" + ObfMapCollector.getMapping("net/minecraft/entity/Entity") + ";FFFFFF)V", false);
			Label l8 = new Label();
			mv.visitLabel(l8);
			mv.visitLineNumber(33, l8);
			Label l9 = new Label();
			mv.visitJumpInsn(GOTO, l9);
			mv.visitLabel(l6);
			mv.visitLineNumber(34, l6);
			mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
			mv.visitVarInsn(ALOAD, 1);
			mv.visitVarInsn(ALOAD, 8);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/entity/EntityLivingBase"), ObfMapCollector.getMapping("isInvisibleToPlayer"), "(L" + ObfMapCollector.getMapping("net/minecraft/entity/player/EntityPlayer") + ";)Z", false);
			Label l10 = new Label();
			mv.visitJumpInsn(IFEQ, l10);
			mv.visitVarInsn(ALOAD, 1);
			mv.visitVarInsn(ALOAD, 8);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/entity/EntityLivingBase"), ObfMapCollector.getMapping("isInvisibleToPlayer"), "(L" + ObfMapCollector.getMapping("net/minecraft/entity/player/EntityPlayer") + ";)Z", false);
			Label l11 = new Label();
			mv.visitJumpInsn(IFEQ, l11);
			mv.visitVarInsn(ALOAD, 9);
			mv.visitJumpInsn(IFNULL, l11);
			mv.visitVarInsn(ALOAD, 9);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/item/ItemStack"), ObfMapCollector.getMapping("getItem"), "()L" + ObfMapCollector.getMapping("net/minecraft/item/Item") + ";", false);
			mv.visitTypeInsn(Opcodes.INSTANCEOF, "trinarybrain/api/IRevealInvisible");
			mv.visitJumpInsn(IFEQ, l11);
			mv.visitVarInsn(ALOAD, 9);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/item/ItemStack"), ObfMapCollector.getMapping("getItem"), "()L" + ObfMapCollector.getMapping("net/minecraft/item/Item") + ";", false);
			mv.visitTypeInsn(Opcodes.CHECKCAST, "trinarybrain/api/IRevealInvisible");
			mv.visitVarInsn(ALOAD, 9);
			mv.visitVarInsn(ALOAD, 8);
			mv.visitVarInsn(ALOAD, 1);
			mv.visitMethodInsn(Opcodes.INVOKEINTERFACE, "trinarybrain/api/IRevealInvisible", "showInvisibleEntity", "(L" + ObfMapCollector.getMapping("net/minecraft/item/ItemStack") + ";L"+ ObfMapCollector.getMapping("net/minecraft/entity/EntityLivingBase") + ";L" + ObfMapCollector.getMapping("net/minecraft/entity/EntityLivingBase") + ";)Z", true);
			mv.visitJumpInsn(IFEQ, l11);
			mv.visitLabel(l10);
			mv.visitLineNumber(36, l10);
			mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glPushMatrix", "()V", false);
			Label l12 = new Label();
			mv.visitLabel(l12);
			mv.visitLineNumber(37, l12);
			mv.visitInsn(FCONST_1);
			mv.visitInsn(FCONST_1);
			mv.visitInsn(FCONST_1);
			mv.visitLdcInsn(new Float("0.15"));
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glColor4f", "(FFFF)V", false);
			Label l13 = new Label();
			mv.visitLabel(l13);
			mv.visitLineNumber(38, l13);
			mv.visitInsn(ICONST_0);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDepthMask", "(Z)V", false);
			Label l14 = new Label();
			mv.visitLabel(l14);
			mv.visitLineNumber(39, l14);
			mv.visitIntInsn(SIPUSH, 3042);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glEnable", "(I)V", false);
			Label l15 = new Label();
			mv.visitLabel(l15);
			mv.visitLineNumber(40, l15);
			mv.visitIntInsn(SIPUSH, 770);
			mv.visitIntInsn(SIPUSH, 771);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glBlendFunc", "(II)V", false);
			Label l16 = new Label();
			mv.visitLabel(l16);
			mv.visitLineNumber(41, l16);
			mv.visitIntInsn(SIPUSH, 516);
			mv.visitLdcInsn(new Float("0.003921569"));
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glAlphaFunc", "(IF)V", false);
			Label l17 = new Label();
			mv.visitLabel(l17);
			mv.visitLineNumber(42, l17);
			mv.visitVarInsn(ALOAD, 0);
			mv.visitFieldInsn(Opcodes.GETFIELD, ObfMapCollector.getMapping("net/minecraft/client/renderer/entity/RendererLivingEntity"), ObfMapCollector.getMapping("mainModel"), "L" + ObfMapCollector.getMapping("net/minecraft/client/model/ModelBase") + ";");
			mv.visitVarInsn(ALOAD, 1);
			mv.visitVarInsn(FLOAD, 2);
			mv.visitVarInsn(FLOAD, 3);
			mv.visitVarInsn(FLOAD, 4);
			mv.visitVarInsn(FLOAD, 5);
			mv.visitVarInsn(FLOAD, 6);
			mv.visitVarInsn(FLOAD, 7);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/client/model/ModelBase"), ObfMapCollector.getMapping("render"), "(L" + ObfMapCollector.getMapping("net/minecraft/entity/Entity") + ";FFFFFF)V", false);
			Label l18 = new Label();
			mv.visitLabel(l18);
			mv.visitLineNumber(43, l18);
			mv.visitIntInsn(SIPUSH, 3042);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDisable", "(I)V", false);
			Label l19 = new Label();
			mv.visitLabel(l19);
			mv.visitLineNumber(44, l19);
			mv.visitIntInsn(SIPUSH, 516);
			mv.visitLdcInsn(new Float("0.1"));
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glAlphaFunc", "(IF)V", false);
			Label l20 = new Label();
			mv.visitLabel(l20);
			mv.visitLineNumber(45, l20);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glPopMatrix", "()V", false);
			Label l21 = new Label();
			mv.visitLabel(l21);
			mv.visitLineNumber(46, l21);
			mv.visitInsn(ICONST_1);
			mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDepthMask", "(Z)V", false);
			Label l22 = new Label();
			mv.visitLabel(l22);
			mv.visitLineNumber(47, l22);
			mv.visitJumpInsn(GOTO, l9);
			mv.visitLabel(l11);
			mv.visitLineNumber(50, l11);
			mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
			mv.visitVarInsn(ALOAD, 0);
			mv.visitFieldInsn(Opcodes.GETFIELD, ObfMapCollector.getMapping("net/minecraft/client/renderer/entity/RendererLivingEntity"), ObfMapCollector.getMapping("mainModel"), "L" + ObfMapCollector.getMapping("net/minecraft/client/model/ModelBase") + ";");
			mv.visitVarInsn(FLOAD, 2);
			mv.visitVarInsn(FLOAD, 3);
			mv.visitVarInsn(FLOAD, 4);
			mv.visitVarInsn(FLOAD, 5);
			mv.visitVarInsn(FLOAD, 6);
			mv.visitVarInsn(FLOAD, 7);
			mv.visitVarInsn(ALOAD, 1);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/client/model/ModelBase"), ObfMapCollector.getMapping("setRotationAngles"), "(FFFFFFL" + ObfMapCollector.getMapping("net/minecraft/entity/Entity") + ";)V", false);
			mv.visitLabel(l9);
			mv.visitLineNumber(52, l9);
			mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
			mv.visitInsn(RETURN);
			Label l23 = new Label();
			mv.visitLabel(l23);
			mv.visitLocalVariable("this", "L" + ObfMapCollector.getMapping("net/minecraft/client/renderer/entity/RendererLivingEntity") + ";", null, l0, l23, 0);
			mv.visitLocalVariable("entity", "L" + ObfMapCollector.getMapping("net/minecraft/entity/EntityLivingBase") + ";", null, l0, l23, 1);
			mv.visitLocalVariable("f1", "F", null, l0, l23, 2);
			mv.visitLocalVariable("f2", "F", null, l0, l23, 3);
			mv.visitLocalVariable("f3", "F", null, l0, l23, 4);
			mv.visitLocalVariable("f4", "F", null, l0, l23, 5);
			mv.visitLocalVariable("f5", "F", null, l0, l23, 6);
			mv.visitLocalVariable("f6", "F", null, l0, l23, 7);
			mv.visitLocalVariable("player", "L" + ObfMapCollector.getMapping("net/minecraft/entity/player/EntityPlayer") + ";", null, l2, l23, 8);
			mv.visitLocalVariable("stack", "L" + ObfMapCollector.getMapping("net/minecraft/item/ItemStack") + ";", null, l3, l23, 9);
			mv.visitMaxs(8, 10);
			mv.visitEnd();
		}
	}
}
