package trinarybrain.magia.naturalis.coremod;

import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraftforge.common.util.FakePlayer;

import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import trinarybrain.magia.naturalis.common.core.Log;

public class ProfileMethod extends MethodVisitor implements Opcodes
{
	private String className;
	private String methodName;

	public ProfileMethod(MethodVisitor mv, String className, String methodName, String desc)
	{
		super(ASM4, mv);
		this.className = className;
		this.methodName = methodName;
		
		// (Lnet/minecraft/entity/EntityLivingBase;FFFFFF)V
		// (Lsv;FFFFFF)V
		if(methodName.equals(ObfMapCollector.getMapping("renderModel")) && desc.equals("(L" + ObfMapCollector.getMapping("net/minecraft/entity/EntityLivingBase") + ";FFFFFF)V"))
		{
			Log.logger.info("Profiled Method " + methodName + " in class " + className+ ".");
			this.mv = null; //set the current method visitor null in order to removes the old method
			Log.logger.info("Replacing " + methodName + " Method-Body in class.");
			mv.visitCode();
			Label l0 = new Label();
			mv.visitLabel(l0);
			mv.visitLineNumber(61, l0);
			mv.visitVarInsn(Opcodes.ALOAD, 0);
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/client/renderer/entity/RendererLivingEntity"), ObfMapCollector.getMapping("bindEntityTexture"), "(L" + ObfMapCollector.getMapping("net/minecraft/entity/Entity") + ";)V", false);
			Label l1 = new Label();
			mv.visitLabel(l1);
			mv.visitLineNumber(62, l1);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, ObfMapCollector.getMapping("net/minecraft/client/Minecraft"), ObfMapCollector.getMapping("getMinecraft"), "()L" + ObfMapCollector.getMapping("net/minecraft/client/Minecraft") + ";", false);
			mv.visitFieldInsn(Opcodes.GETFIELD, ObfMapCollector.getMapping("net/minecraft/client/Minecraft"), ObfMapCollector.getMapping("thePlayer"), "L" + ObfMapCollector.getMapping("net/minecraft/client/entity/EntityClientPlayerMP") + ";");
			mv.visitVarInsn(Opcodes.ASTORE, 8);
			Label l2 = new Label();
			mv.visitLabel(l2);
			mv.visitLineNumber(63, l2);
			mv.visitVarInsn(Opcodes.ALOAD, 8);
			mv.visitFieldInsn(Opcodes.GETFIELD, ObfMapCollector.getMapping("net/minecraft/entity/player/EntityPlayer"), ObfMapCollector.getMapping("inventory"), "L" + ObfMapCollector.getMapping("net/minecraft/entity/player/InventoryPlayer") + ";");
			mv.visitInsn(Opcodes.ICONST_3);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/entity/player/InventoryPlayer"), ObfMapCollector.getMapping("armorItemInSlot"), "(I)L" + ObfMapCollector.getMapping("net/minecraft/item/ItemStack") + ";", false);
			mv.visitVarInsn(Opcodes.ASTORE, 9);
			Label l3 = new Label();
			mv.visitLabel(l3);
			mv.visitLineNumber(65, l3);
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/entity/EntityLivingBase"), ObfMapCollector.getMapping("isInvisible"), "()Z", false);
			Label l4 = new Label();
			mv.visitJumpInsn(Opcodes.IFNE, l4);
			Label l5 = new Label();
			mv.visitLabel(l5);
			mv.visitLineNumber(67, l5);
			mv.visitVarInsn(Opcodes.ALOAD, 0);
			mv.visitFieldInsn(Opcodes.GETFIELD, ObfMapCollector.getMapping("net/minecraft/client/renderer/entity/RendererLivingEntity"), ObfMapCollector.getMapping("mainModel"), "L" + ObfMapCollector.getMapping("net/minecraft/client/model/ModelBase") + ";");
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitVarInsn(Opcodes.FLOAD, 2);
			mv.visitVarInsn(Opcodes.FLOAD, 3);
			mv.visitVarInsn(Opcodes.FLOAD, 4);
			mv.visitVarInsn(Opcodes.FLOAD, 5);
			mv.visitVarInsn(Opcodes.FLOAD, 6);
			mv.visitVarInsn(Opcodes.FLOAD, 7);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/client/model/ModelBase"), ObfMapCollector.getMapping("render"), "(L" + ObfMapCollector.getMapping("net/minecraft/entity/Entity") + ";FFFFFF)V", false);
			Label l6 = new Label();
			mv.visitLabel(l6);
			mv.visitLineNumber(68, l6);
			Label l7 = new Label();
			mv.visitJumpInsn(Opcodes.GOTO, l7);
			mv.visitLabel(l4);
			mv.visitLineNumber(69, l4);
			mv.visitFrame(Opcodes.F_APPEND,2, new Object[] {ObfMapCollector.getMapping("net/minecraft/entity/player/EntityPlayer"), ObfMapCollector.getMapping("net/minecraft/item/ItemStack")}, 0, null);
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitVarInsn(Opcodes.ALOAD, 8);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/entity/EntityLivingBase"), ObfMapCollector.getMapping("isInvisibleToPlayer"), "(L" + ObfMapCollector.getMapping("net/minecraft/entity/player/EntityPlayer") + ";)Z", false);
			Label l8 = new Label();
			mv.visitJumpInsn(Opcodes.IFEQ, l8);
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitVarInsn(Opcodes.ALOAD, 8);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/entity/EntityLivingBase"), ObfMapCollector.getMapping("isInvisibleToPlayer"), "(L" + ObfMapCollector.getMapping("net/minecraft/entity/player/EntityPlayer") + ";)Z", false);
			Label l9 = new Label();
			mv.visitJumpInsn(Opcodes.IFEQ, l9);
			mv.visitVarInsn(Opcodes.ALOAD, 9);
			mv.visitJumpInsn(Opcodes.IFNULL, l9);
			mv.visitVarInsn(Opcodes.ALOAD, 9);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/item/ItemStack"), ObfMapCollector.getMapping("getItem"), "()L" + ObfMapCollector.getMapping("net/minecraft/item/Item") + ";", false);
			mv.visitTypeInsn(Opcodes.INSTANCEOF, "trinarybrain/magia/naturalis/api/IRevealInvisible");
			mv.visitJumpInsn(Opcodes.IFEQ, l9);
			mv.visitVarInsn(Opcodes.ALOAD, 9);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/item/ItemStack"), ObfMapCollector.getMapping("getItem"), "()L" + ObfMapCollector.getMapping("net/minecraft/item/Item") + ";", false);
			mv.visitTypeInsn(Opcodes.CHECKCAST, "trinarybrain/magia/naturalis/api/IRevealInvisible");
			mv.visitVarInsn(Opcodes.ALOAD, 9);
			mv.visitVarInsn(Opcodes.ALOAD, 8);
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitMethodInsn(Opcodes.INVOKEINTERFACE, "trinarybrain/magia/naturalis/api/IRevealInvisible", "showInvisibleEntity", "(L" + ObfMapCollector.getMapping("net/minecraft/item/ItemStack") + ";L"+ ObfMapCollector.getMapping("net/minecraft/entity/EntityLivingBase") + ";L" + ObfMapCollector.getMapping("net/minecraft/entity/EntityLivingBase") + ";)Z", true);
			mv.visitJumpInsn(Opcodes.IFEQ, l9);
			mv.visitLabel(l8);
			mv.visitLineNumber(71, l8);
			mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glPushMatrix", "()V", false);
			Label l10 = new Label();
			mv.visitLabel(l10);
			mv.visitLineNumber(72, l10);
			mv.visitInsn(Opcodes.FCONST_1);
			mv.visitInsn(Opcodes.FCONST_1);
			mv.visitInsn(Opcodes.FCONST_1);
			mv.visitLdcInsn(new Float("0.15"));
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glColor4f", "(FFFF)V", false);
			Label l11 = new Label();
			mv.visitLabel(l11);
			mv.visitLineNumber(73, l11);
			mv.visitInsn(Opcodes.ICONST_0);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDepthMask", "(Z)V", false);
			Label l12 = new Label();
			mv.visitLabel(l12);
			mv.visitLineNumber(74, l12);
			mv.visitIntInsn(Opcodes.SIPUSH, 3042);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glEnable", "(I)V", false);
			Label l13 = new Label();
			mv.visitLabel(l13);
			mv.visitLineNumber(75, l13);
			mv.visitIntInsn(Opcodes.SIPUSH, 770);
			mv.visitIntInsn(Opcodes.SIPUSH, 771);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glBlendFunc", "(II)V", false);
			Label l14 = new Label();
			mv.visitLabel(l14);
			mv.visitLineNumber(76, l14);
			mv.visitIntInsn(Opcodes.SIPUSH, 516);
			mv.visitLdcInsn(new Float("0.003921569"));
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glAlphaFunc", "(IF)V", false);
			Label l15 = new Label();
			mv.visitLabel(l15);
			mv.visitLineNumber(77, l15);
			mv.visitVarInsn(Opcodes.ALOAD, 0);
			mv.visitFieldInsn(Opcodes.GETFIELD, ObfMapCollector.getMapping("net/minecraft/client/renderer/entity/RendererLivingEntity"), ObfMapCollector.getMapping("mainModel"), "L" + ObfMapCollector.getMapping("net/minecraft/client/model/ModelBase") + ";");
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitVarInsn(Opcodes.FLOAD, 2);
			mv.visitVarInsn(Opcodes.FLOAD, 3);
			mv.visitVarInsn(Opcodes.FLOAD, 4);
			mv.visitVarInsn(Opcodes.FLOAD, 5);
			mv.visitVarInsn(Opcodes.FLOAD, 6);
			mv.visitVarInsn(Opcodes.FLOAD, 7);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/client/model/ModelBase"), ObfMapCollector.getMapping("render"), "(L" + ObfMapCollector.getMapping("net/minecraft/entity/Entity") + ";FFFFFF)V", false);
			Label l16 = new Label();
			mv.visitLabel(l16);
			mv.visitLineNumber(78, l16);
			mv.visitIntInsn(Opcodes.SIPUSH, 3042);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDisable", "(I)V", false);
			Label l17 = new Label();
			mv.visitLabel(l17);
			mv.visitLineNumber(79, l17);
			mv.visitIntInsn(Opcodes.SIPUSH, 516);
			mv.visitLdcInsn(new Float("0.1"));
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glAlphaFunc", "(IF)V", false);
			Label l18 = new Label();
			mv.visitLabel(l18);
			mv.visitLineNumber(80, l18);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glPopMatrix", "()V", false);
			Label l19 = new Label();
			mv.visitLabel(l19);
			mv.visitLineNumber(81, l19);
			mv.visitInsn(Opcodes.ICONST_1);
			mv.visitMethodInsn(Opcodes.INVOKESTATIC, "org/lwjgl/opengl/GL11", "glDepthMask", "(Z)V", false);
			Label l20 = new Label();
			mv.visitLabel(l20);
			mv.visitLineNumber(82, l20);
			mv.visitJumpInsn(Opcodes.GOTO, l7);
			mv.visitLabel(l9);
			mv.visitLineNumber(85, l9);
			mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
			mv.visitVarInsn(Opcodes.ALOAD, 0);
			mv.visitFieldInsn(Opcodes.GETFIELD, ObfMapCollector.getMapping("net/minecraft/client/renderer/entity/RendererLivingEntity"), ObfMapCollector.getMapping("mainModel"), "L" + ObfMapCollector.getMapping("net/minecraft/client/model/ModelBase") + ";");
			mv.visitVarInsn(Opcodes.FLOAD, 2);
			mv.visitVarInsn(Opcodes.FLOAD, 3);
			mv.visitVarInsn(Opcodes.FLOAD, 4);
			mv.visitVarInsn(Opcodes.FLOAD, 5);
			mv.visitVarInsn(Opcodes.FLOAD, 6);
			mv.visitVarInsn(Opcodes.FLOAD, 7);
			mv.visitVarInsn(Opcodes.ALOAD, 1);
			mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ObfMapCollector.getMapping("net/minecraft/client/model/ModelBase"), ObfMapCollector.getMapping("setRotationAngles"), "(FFFFFFL" + ObfMapCollector.getMapping("net/minecraft/entity/Entity") + ";)V", false);
			mv.visitLabel(l7);
			mv.visitLineNumber(87, l7);
			mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
			mv.visitInsn(Opcodes.RETURN);
			Label l21 = new Label();
			mv.visitLabel(l21);
			mv.visitLocalVariable("this", "L" + ObfMapCollector.getMapping("net/minecraft/client/renderer/entity/RendererLivingEntity") + ";", null, l0, l21, 0);
			mv.visitLocalVariable("entity", "L" + ObfMapCollector.getMapping("net/minecraft/entity/EntityLivingBase") + ";", null, l0, l21, 1);
			mv.visitLocalVariable("f1", "F", null, l0, l21, 2);
			mv.visitLocalVariable("f2", "F", null, l0, l21, 3);
			mv.visitLocalVariable("f3", "F", null, l0, l21, 4);
			mv.visitLocalVariable("f4", "F", null, l0, l21, 5);
			mv.visitLocalVariable("f5", "F", null, l0, l21, 6);
			mv.visitLocalVariable("f6", "F", null, l0, l21, 7);
			mv.visitLocalVariable("player", "L" + ObfMapCollector.getMapping("net/minecraft/entity/player/EntityPlayer") + ";", null, l2, l21, 8);
			mv.visitLocalVariable("stack", "L" + ObfMapCollector.getMapping("net/minecraft/item/ItemStack") + ";", null, l3, l21, 9);
			mv.visitMaxs(8, 10);
			mv.visitEnd();
		}
	}
}
